import { listPdfExports } from '@/app/data/actions/pdf'
import { getUserRoleAndProjects } from '@/app/data/actions/auth-helpers'
import { getProjectAssignments } from '@/app/data/actions/projects'
import { format } from 'date-fns'
import { Download } from 'lucide-react'
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card'
import PdfExportDownloadButton from './PdfExportDownloadButton'

export default async function ExportsPage() {
  const roleInfo = await getUserRoleAndProjects()
  const allExports = await listPdfExports()

  // For PMs, only show exports from users assigned to their projects
  let exports = allExports
  if (roleInfo?.pmProjectIds) {
    const assignedUserSets = await Promise.all(
      roleInfo.pmProjectIds.map(pid => getProjectAssignments(pid))
    )
    const allowedUserIds = new Set(assignedUserSets.flat())
    exports = allExports.filter((exp: any) => allowedUserIds.has(exp.user_id))
  }

  return (
    <div className="space-y-6">
      <div>
        <h2 className="text-3xl font-bold tracking-tight flex items-center gap-2">
          <Download className="h-8 w-8 text-primary" /> PDF Exports
        </h2>
        <p className="text-muted-foreground mt-1">Monthly timesheet PDFs generated by employees.</p>
      </div>

      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Download className="h-5 w-5" /> All Exports
          </CardTitle>
          <CardDescription>{exports.length} export{exports.length !== 1 ? 's' : ''} found.</CardDescription>
        </CardHeader>
        <CardContent>
          {exports.length === 0 ? (
            <p className="text-sm text-muted-foreground py-4 text-center">No PDF exports yet.</p>
          ) : (
            <div className="overflow-x-auto">
              <table className="w-full text-sm">
                <thead>
                  <tr className="border-b">
                    <th className="text-left py-2 px-3 font-medium">Employee</th>
                    <th className="text-left py-2 px-3 font-medium">Month</th>
                    <th className="text-left py-2 px-3 font-medium">Generated</th>
                    <th className="text-right py-2 px-3 font-medium">Action</th>
                  </tr>
                </thead>
                <tbody>
                  {exports.map((exp: any) => (
                    <tr key={exp.id} className="border-b last:border-0">
                      <td className="py-2 px-3">{exp.profiles?.full_name || 'Unknown'}</td>
                      <td className="py-2 px-3">{exp.month}</td>
                      <td className="py-2 px-3">{exp.created_at ? format(new Date(exp.created_at), 'dd.MM.yyyy HH:mm') : '-'}</td>
                      <td className="py-2 px-3 text-right">
                        <PdfExportDownloadButton exportId={exp.id} />
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  )
}
