-- LOCAL FIXTURE for DCS 1b.07 (document profile). NEVER run against scl-dev or prod.
--
-- Why it exists: on scl-dev every dcs.documents row has current_revision_id NULL
-- and dcs.revisions / dcs.files are empty (read 2026-09-19), because nothing
-- creates a revision until 1b.08 and nothing uploads a file until 1b.09. The
-- right-hand panel of the profile is therefore built against the schema and
-- proven here, on a local stack.
--
-- What it is NOT: a migration (it lives outside supabase/migrations/, so
-- `supabase db push` cannot ship it), not part of seed.sql (a plain
-- `supabase db reset` stays exactly as before), and not a pgTAP test
-- (supabase/tests/ would run it as one). Load it by hand after a reset:
--
--   docker exec -i -e PGOPTIONS='-c app.local_fixture=yes' \
--     supabase_db_Seaclouds_management_system \
--     psql -U postgres -v ON_ERROR_STOP=1 < supabase/fixtures/document_profile.sql
--
-- The guard below refuses to run without app.local_fixture=yes, which a
-- dashboard SQL editor or an MCP execute_sql call will never set. It is a
-- seatbelt, not a security boundary.
--
-- Idempotent: every row has a fixed id and is inserted only when absent, so it
-- can be loaded twice. (The SCL number is generated by the 1b.02 trigger on the
-- first load and left alone afterwards.)
--
-- Cast (all passwords: password123, same as supabase/seed.sql):
--   dc.profile@local.test       dc of SC2602, with a VERIFIED TOTP factor so the
--                               browser can reach aal2. Secret: JBSWY3DPEHPK3PXP
--   orig.profile@local.test     orig of SC2602 — the "plain member" session
--   outsider.profile@local.test no role and no assignment anywhere — the 404 session
-- plus the seed's own admin, tjezionekspam@gmail.com.
--
-- Rows: two documents on SC2602 (project 6c0909ce-…). One has a current
-- revision 'A' and one file; the other has no revision at all, which is the
-- "No revision yet" case the real documents show today.
--
-- It also flips SC2602's mdr_settings.cpy_numbering to true: the seed has it
-- false, and the CPY field is only editable on a project with a CPY track.
-- Local only — scl-dev and prod are not touched by any of this.

do $$
begin
  if coalesce(current_setting('app.local_fixture', true), '') <> 'yes' then
    raise exception
      'supabase/fixtures/document_profile.sql is a LOCAL-ONLY fixture. Run it with PGOPTIONS=''-c app.local_fixture=yes'' against the local stack, never against scl-dev or prod.';
  end if;
end
$$;

-- One transaction: the temp table below is `on commit drop`, and a half-loaded
-- fixture (users without their roles) is worse than none.
begin;
set local search_path = public, extensions;

-- ============================================================
-- Users, identities, profiles, module access
-- ============================================================
create temp table fx_users (id uuid, email text, full_name text) on commit drop;
insert into fx_users values
  ('f1000000-0000-4000-8000-000000000001', 'dc.profile@local.test',       'Dorota Controller'),
  ('f1000000-0000-4000-8000-000000000002', 'orig.profile@local.test',     'Oskar Originator'),
  ('f1000000-0000-4000-8000-000000000003', 'outsider.profile@local.test', 'Olga Outsider');

insert into auth.users (
  instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
  raw_app_meta_data, raw_user_meta_data, created_at, updated_at,
  confirmation_token, email_change, email_change_token_new, recovery_token,
  phone_change, phone_change_token, email_change_token_current, email_change_confirm_status)
select
  '00000000-0000-0000-0000-000000000000', u.id, 'authenticated', 'authenticated',
  u.email, extensions.crypt('password123', extensions.gen_salt('bf')), now(),
  '{"provider":"email","providers":["email"]}'::jsonb, jsonb_build_object('full_name', u.full_name),
  now(), now(), '', '', '', '', '', '', '', 0
from fx_users u
where not exists (select 1 from auth.users x where x.id = u.id);

insert into auth.identities (id, user_id, provider_id, provider, identity_data, last_sign_in_at, created_at, updated_at)
select gen_random_uuid(), u.id, u.id::text, 'email',
       jsonb_build_object('sub', u.id::text, 'email', u.email, 'email_verified', true),
       now(), now(), now()
from fx_users u
where not exists (select 1 from auth.identities i where i.user_id = u.id);

-- The profile row is created by a trigger on auth.users, exactly as in seed.sql.
update public.profiles p set full_name = u.full_name, role = 'employee'
from fx_users u where p.id = u.id;

-- Without this the proxy sends the user back to the TES portal (hasModuleAccess).
insert into public.module_permissions (user_id, module)
select u.id, 'dcs' from fx_users u
where not exists (select 1 from public.module_permissions m where m.user_id = u.id and m.module = 'dcs');

insert into dcs.project_roles (project_id, user_id, role)
select '6c0909ce-9b74-4bda-8e92-10811ff5a0fc'::uuid, u.id, r.role::dcs.project_role
from (values
  ('f1000000-0000-4000-8000-000000000001'::uuid, 'dc'),
  ('f1000000-0000-4000-8000-000000000002'::uuid, 'orig')
) as r(uid, role)
join fx_users u on u.id = r.uid
where not exists (
  select 1 from dcs.project_roles x
   where x.project_id = '6c0909ce-9b74-4bda-8e92-10811ff5a0fc' and x.user_id = u.id and x.role = r.role::dcs.project_role
);

-- A verified TOTP factor for the DC, so a browser session can reach aal2 by
-- typing a code computed from the secret above (no QR enrolment in the way).
insert into auth.mfa_factors (id, user_id, friendly_name, factor_type, status, created_at, updated_at, secret)
select 'f2000000-0000-4000-8000-000000000001', 'f1000000-0000-4000-8000-000000000001',
       'fixture authenticator', 'totp', 'verified', now(), now(), 'JBSWY3DPEHPK3PXP'
where not exists (select 1 from auth.mfa_factors where id = 'f2000000-0000-4000-8000-000000000001');

-- ============================================================
-- SC2602 runs a CPY track (the seed has it off)
-- ============================================================
update dcs.mdr_settings set cpy_numbering = true
 where project_id = '6c0909ce-9b74-4bda-8e92-10811ff5a0fc';

-- ============================================================
-- Two documents: one with a current revision and a file, one without
-- ============================================================
-- Sessionless (postgres), so the CPY/DC guard and the SCL-number generator run
-- as they do for a migration: the generator assigns the number, the DC check is
-- bypassed (auth.uid() is null).
insert into dcs.documents (
  id, project_id, title, doc_type_id, discipline_id, area_id, language_id, workflow_status_id,
  originator_id, checker_id, approver_id, budget_hours)
select
  d.id, '6c0909ce-9b74-4bda-8e92-10811ff5a0fc', d.title,
  (select id from dcs.dictionaries where dict_type = 'doc_type' and code = 'RA'),
  (select id from dcs.dictionaries where dict_type = 'discipline' and code = 'A00'),
  (select id from dcs.dictionaries where dict_type = 'area' and code = '00'),
  (select id from dcs.dictionaries where dict_type = 'language' and code = 'EN'),
  (select id from dcs.dictionaries where dict_type = 'workflow_status' and code = d.status),
  'f1000000-0000-4000-8000-000000000002',
  null::uuid,                                   -- checker: unstaffed
  'f1000000-0000-4000-8000-000000000001',
  60
from (values
  (1, 'f3000000-0000-4000-8000-000000000001'::uuid, 'Fixture — geophysical survey report (has a current revision)', 'IDC'),
  (2, 'f3000000-0000-4000-8000-000000000002'::uuid, 'Fixture — document without a revision',                       'NOT_STARTED')
) as d(ord, id, title, status)
where not exists (select 1 from dcs.documents x where x.id = d.id)
-- The 1b.02 generator numbers rows in the order they arrive; without this the
-- planner may hand it the second row first, and which document is -0001 would
-- differ from one load to the next.
order by d.ord;

insert into dcs.revisions (
  id, document_id, project_id, scl_revision, cpy_revision,
  step_id, reason_for_issue, revision_date, status_id, created_by)
select
  'f4000000-0000-4000-8000-000000000001', d.id, d.project_id, 'A', 'R1',
  (select id from dcs.dictionaries where dict_type = 'workflow_step' and code = 'IDC'),
  'Issued for internal discipline check',
  date '2026-09-19',
  (select id from dcs.dictionaries where dict_type = 'workflow_status' and code = 'IDC'),
  'f1000000-0000-4000-8000-000000000002'
from dcs.documents d
where d.id = 'f3000000-0000-4000-8000-000000000001'
  and not exists (select 1 from dcs.revisions x where x.id = 'f4000000-0000-4000-8000-000000000001');

-- A file row with no storage object behind it: the panel lists metadata only
-- (downloads and signed URLs are 1b.09), so storage_path stays NULL.
insert into dcs.files (
  id, revision_id, project_id, file_kind, file_name, original_name, mime_type, size_bytes, uploaded_by)
select
  'f5000000-0000-4000-8000-000000000001', r.id, r.project_id, 'original',
  d.scl_doc_number || '_A_IDC_2026-09-19_01.docx', 'Survey report draft.docx',
  'application/vnd.openxmlformats-officedocument.wordprocessingml.document', 2411520,
  'f1000000-0000-4000-8000-000000000002'
from dcs.revisions r
join dcs.documents d on d.id = r.document_id
where r.id = 'f4000000-0000-4000-8000-000000000001'
  and not exists (select 1 from dcs.files x where x.id = 'f5000000-0000-4000-8000-000000000001');

update dcs.documents set current_revision_id = 'f4000000-0000-4000-8000-000000000001'
 where id = 'f3000000-0000-4000-8000-000000000001'
   and current_revision_id is distinct from 'f4000000-0000-4000-8000-000000000001';

commit;

-- What the task's verification asks to read back:
select d.scl_doc_number, d.current_revision_id,
       (select count(*) from dcs.files f where f.revision_id = d.current_revision_id) as files
  from dcs.documents d
 where d.id in ('f3000000-0000-4000-8000-000000000001', 'f3000000-0000-4000-8000-000000000002')
 order by d.scl_doc_number;
